/** URL → label per locale (shared technical URLs use same label) */
export const linkLabels = {
  "https://en-us.support.motorola.com/app/answers/detail/a_id/150888": {
    en: "Motorola Rescue and Smart Assistant",
    cs: "Motorola Rescue and Smart Assistant",
    pl: "Motorola Rescue and Smart Assistant",
    de: "Motorola Rescue and Smart Assistant",
    hu: "Motorola Rescue and Smart Assistant",
    sk: "Motorola Rescue and Smart Assistant",
  },
  "https://en-us.support.motorola.com/app/answers/detail/a_id/88481": {
    en: "Motorola USB Drivers",
    cs: "Motorola USB ovladače",
    pl: "Sterowniki USB Motorola",
    de: "Motorola USB-Treiber",
    hu: "Motorola USB illesztőprogramok",
    sk: "Motorola USB Drivers",
  },
  "https://en-us.support.motorola.com/app/standalone/bootloader/unlock-your-device-a": {
    en: "Motorola Bootloader Unlock",
    cs: "Motorola Bootloader Unlock",
    pl: "Motorola Bootloader Unlock",
    de: "Motorola Bootloader Unlock",
    hu: "Motorola Bootloader Unlock",
    sk: "Motorola Bootloader Unlock",
  },
  "https://androidfilehost.com/?w=files&flist=1&s=Motorola": {
    en: "Android File Host (Motorola)",
    cs: "Android File Host (Motorola)",
    pl: "Android File Host (Motorola)",
    de: "Android File Host (Motorola)",
    hu: "Android File Host (Motorola)",
    sk: "Android File Host (Motorola)",
  },
  "https://mirrors.lolinet.com/firmware/lenomola/": {
    en: "Lolinet Motorola Firmware",
    cs: "Lolinet Motorola Firmware",
    pl: "Lolinet Motorola Firmware",
    de: "Lolinet Motorola Firmware",
    hu: "Lolinet Motorola firmware",
    sk: "Lolinet Motorola Firmware",
  },

  "https://developer.samsung.com/android-usb-driver": {
    en: "Samsung USB Driver",
    cs: "Samsung USB ovladač",
    pl: "Sterownik USB Samsung",
    de: "Samsung USB-Treiber",
    hu: "Samsung USB illesztőprogram",
    sk: "Samsung USB Driver",
  },
  "https://www.samsung.com/us/support/owners/app/smart-switch": {
    en: "Samsung Smart Switch",
    cs: "Samsung Smart Switch",
    pl: "Samsung Smart Switch",
    de: "Samsung Smart Switch",
    hu: "Samsung Smart Switch",
    sk: "Samsung Smart Switch",
  },
  "https://forum.xda-developers.com/t/odin-multi-download-android-rom-flash-tool.3393441/": {
    en: "Odin3 (XDA)",
    cs: "Odin3 (XDA)",
    pl: "Odin3 (XDA)",
    de: "Odin3 (XDA)",
    hu: "Odin3 (XDA)",
    sk: "Odin3 (XDA)",
  },
  "https://forum.xda-developers.com/t/tool-frija-samsung-firmware-downloader-checker.3910834/": {
    en: "Frija — Samsung firmware downloader",
    cs: "Frija — Samsung firmware downloader",
    pl: "Frija — Samsung firmware downloader",
    de: "Frija — Samsung Firmware-Downloader",
    hu: "Frija — Samsung firmware letöltő",
    sk: "Frija — Samsung firmware downloader",
  },
  "https://www.sammobile.com/firmwares/": {
    en: "SamMobile Firmware",
    cs: "SamMobile Firmware",
    pl: "SamMobile Firmware",
    de: "SamMobile Firmware",
    hu: "SamMobile",
    sk: "SamMobile Firmware",
  },
  "https://forum.xda-developers.com/t/guide-odin-pit-file.2191465/": {
    en: "Samsung Odin PIT guide (XDA)",
    cs: "Samsung Odin PIT návod (XDA)",
    pl: "Samsung Odin PIT poradnik (XDA)",
    de: "Samsung Odin PIT-Anleitung (XDA)",
    hu: "Samsung Odin PIT útmutató (XDA)",
    sk: "Samsung Odin PIT guide (XDA)",
  },
  "https://www.mediatek.com/": {
    en: "MediaTek (official)",
    cs: "MediaTek (oficiálně)",
    pl: "MediaTek (oficjalnie)",
    de: "MediaTek (offiziell)",
    hu: "MediaTek (hivatalos)",
    sk: "MediaTek (oficiálne)",
  },
  "https://spflashtool.com/download/": {
    en: "SP Flash Tool",
    cs: "SP Flash Tool",
    pl: "SP Flash Tool",
    de: "SP Flash Tool",
    hu: "SP Flash Tool",
    sk: "SP Flash Tool",
  },
  "https://androidmtk.com/download-mtk-usb-vcom-drivers": {
    en: "MediaTek USB VCOM Driver",
    cs: "MediaTek USB VCOM ovladač",
    pl: "MediaTek USB VCOM Driver",
    de: "MediaTek USB VCOM-Treiber",
    hu: "MediaTek USB VCOM illesztőprogram",
    sk: "MediaTek USB VCOM Driver",
  },
  "https://androidmtk.com/": {
    en: "Android MTK guides",
    cs: "Android MTK návody",
    pl: "Android MTK poradniki",
    de: "Android MTK-Anleitungen",
    hu: "Android MTK útmutatók",
    sk: "Android MTK návody",
  },
  "https://www.needrom.com/category/mtk/": {
    en: "Needrom MTK firmware",
    cs: "Needrom MTK firmware",
    pl: "Needrom MTK firmware",
    de: "Needrom MTK-Firmware",
    hu: "Needrom MTK firmware",
    sk: "Needrom MTK firmware",
  },
  "https://www.unisoc.com/": {
    en: "Unisoc (official)",
    cs: "Unisoc (oficiálně)",
    pl: "Unisoc (oficjalnie)",
    de: "Unisoc (offiziell)",
    hu: "Unisoc (hivatalos)",
    sk: "Unisoc (oficiálne)",
  },
  "https://www.needrom.com/category/unisoc/": {
    en: "Needrom Unisoc firmware",
    cs: "Needrom Unisoc firmware",
    pl: "Needrom Unisoc firmware",
    de: "Needrom Unisoc-Firmware",
    hu: "Unisoc firmware (Needrom)",
    sk: "Needrom Unisoc firmware",
  },
  "https://developer.android.com/studio/run/emulator#recovery": {
    en: "Android Recovery (official)",
    cs: "Android Recovery (oficiálně)",
    pl: "Android Recovery (oficjalnie)",
    de: "Android Recovery (offiziell)",
    hu: "Android Recovery (hivatalos)",
    sk: "Android Recovery (oficiálne)",
  },
  "https://developer.android.com/studio/command-line/adb#copyfiles": {
    en: "ADB sideload (official)",
    cs: "ADB sideload (oficiálně)",
    pl: "ADB sideload (oficjalnie)",
    de: "ADB Sideload (offiziell)",
    hu: "ADB sideload (hivatalos)",
    sk: "ADB sideload (oficiálne)",
  },
  "https://forum.xda-developers.com/": {
    en: "XDA Bootloop forum",
    cs: "XDA Bootloop fórum",
    pl: "XDA Bootloop forum",
    de: "XDA Bootloop-Forum",
    hu: "XDA Bootloop fórum",
    sk: "XDA Bootloop poradňa",
  },
  "https://forum.xda-developers.com/f/moto-g.5208/": {
    en: "Moto G XDA forum",
    cs: "Moto G XDA fórum",
    pl: "Moto G XDA forum",
    de: "Moto G XDA-Forum",
    hu: "Moto G XDA fórum",
    sk: "Moto G XDA poradňa",
  },
  "https://qpsttool.com/": {
    en: "QPST Flash Tool",
    cs: "QPST Flash Tool",
    pl: "QPST Flash Tool",
    de: "QPST Flash Tool",
    hu: "QPST Flash Tool",
    sk: "QPST Flash Tool",
  },
  "https://forum.xda-developers.com/t/qualcomm-edl-mode-9008.3602067/": {
    en: "XDA Qualcomm EDL guide",
    cs: "XDA Qualcomm EDL návod",
    pl: "XDA Qualcomm EDL poradnik",
    de: "XDA Qualcomm EDL-Anleitung",
    hu: "XDA Qualcomm EDL útmutató",
    sk: "XDA Qualcomm EDL guide",
  },
  "https://xiaomiflashtool.com/": {
    en: "Mi Flash Tool (Xiaomi EDL)",
    cs: "Mi Flash Tool (Xiaomi EDL)",
    pl: "Mi Flash Tool (Xiaomi EDL)",
    de: "Mi Flash Tool (Xiaomi EDL)",
    hu: "Mi Flash Tool",
    sk: "Mi Flash Tool (Xiaomi EDL)",
  },
  "https://developer.android.com/tools/releases/platform-tools": {
    en: "Platform Tools",
    cs: "Platform Tools",
    pl: "Platform Tools",
    de: "Platform Tools",
    hu: "Platform Tools",
    sk: "Platform Tools",
  },
  "https://developer.android.com/tools/adb": {
    en: "ADB (official documentation)",
    cs: "ADB (oficiální dokumentace)",
    pl: "ADB (oficjalna dokumentacja)",
    de: "ADB (offizielle Dokumentation)",
    hu: "ADB (hivatalos dokumentáció)",
    sk: "ADB (oficiálna dokumentácia)",
  },
  "https://developer.android.com/studio/run/win-usb": {
    en: "Google USB Driver (Windows)",
    cs: "Google USB ovladač (Windows)",
    pl: "Google USB Driver (Windows)",
    de: "Google USB-Treiber (Windows)",
    hu: "Google USB illesztőprogram (Windows)",
    sk: "Google USB Driver (Windows)",
  },
  "https://androidmtk.com/download-research-download-tool": {
    en: "Research Download Tool",
    cs: "Research Download Tool",
    pl: "Research Download Tool",
    de: "Research Download Tool",
    hu: "Research Download Tool",
    sk: "Research Download Tool",
  },
  "https://www.samsung.com/us/support/downloads/": {
    en: "Samsung Support Downloads",
    cs: "Samsung Support Downloads",
    pl: "Samsung Support Downloads",
    de: "Samsung Support Downloads",
    hu: "Samsung Support Downloads",
    sk: "Samsung Support Downloads",
  },
  "https://en.miui.com/unlock/": {
    en: "Mi Unlock (official)",
    cs: "Mi Unlock (oficiálně)",
    pl: "Mi Unlock (oficjalnie)",
    de: "Mi Unlock (offiziell)",
    hu: "Mi Unlock (hivatalos)",
    sk: "Mi Unlock (oficiálne)",
  },
  "https://hyperos.mi.com/": {
    en: "Xiaomi HyperOS (official info)",
    cs: "Xiaomi HyperOS (oficiální info)",
    pl: "Xiaomi HyperOS (oficjalne info)",
    de: "Xiaomi HyperOS (offizielle Info)",
    hu: "Xiaomi HyperOS (hivatalos info)",
    sk: "Xiaomi HyperOS (oficiálne info)",
  },
  "https://xmfirmwareupdater.com/hyperos/": {
    en: "Xiaomi ROM catalog (HyperOS / MIUI)",
    cs: "Xiaomi ROM katalog (HyperOS / MIUI)",
    pl: "Katalog ROM Xiaomi (HyperOS / MIUI)",
    de: "Xiaomi ROM-Katalog (HyperOS / MIUI)",
    hu: "Xiaomi ROM katalógus (HyperOS / MIUI)",
    sk: "Xiaomi ROM katalóg (HyperOS / MIUI)",
  },
  "https://www.mi.com/global/support/tools": {
    en: "Xiaomi official tools",
    cs: "Xiaomi oficiální nástroje",
    pl: "Oficjalne narzędzia Xiaomi",
    de: "Xiaomi offizielle Tools",
    hu: "Xiaomi hivatalos eszközök",
    sk: "Xiaomi oficiálne nástroje",
  },
  "https://www.oneplus.com/support/softwareupgrade": {
    en: "OnePlus software upgrade",
    cs: "OnePlus software upgrade",
    pl: "OnePlus software upgrade",
    de: "OnePlus Software-Upgrade",
    hu: "OnePlus szoftverfrissítés",
    sk: "OnePlus software upgrade",
  },
  "https://support.google.com/android/answer/2812853?hl=sk": {
    en: "Google FRP help (official)",
    cs: "Google FRP nápověda (oficiálně)",
    pl: "Google FRP pomoc (oficjalnie)",
    de: "Google FRP-Hilfe (offiziell)",
    hu: "Google FRP súgó (hivatalos)",
    sk: "Google FRP help (oficiálne)",
  },
  "https://www.virustotal.com/": {
    en: "VirusTotal (file verification)",
    cs: "VirusTotal (ověření souborů)",
    pl: "VirusTotal (weryfikacja plików)",
    de: "VirusTotal (Dateiprüfung)",
    hu: "VirusTotal (fájl ellenőrzés)",
    sk: "VirusTotal (overenie súborov)",
  },
  "https://vercel.com/legal/acceptable-use-policy": {
    en: "Vercel Acceptable Use Policy",
    cs: "Vercel Acceptable Use Policy",
    pl: "Vercel Acceptable Use Policy",
    de: "Vercel Acceptable Use Policy",
    hu: "Vercel Acceptable Use Policy",
    sk: "Vercel Acceptable Use Policy",
  },
  "https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/certutil": {
    en: "SHA256 hash (certutil — Windows)",
    cs: "SHA256 hash (certutil — Windows)",
    pl: "SHA256 hash (certutil — Windows)",
    de: "SHA256-Hash (certutil — Windows)",
    hu: "SHA256 hash (certutil — Windows)",
    sk: "SHA256 hash (certutil — Windows)",
  },
  "https://github.com/JVVMEDIA/flash-diagnostics-hub": {
    en: "GitHub repository (source code)",
    cs: "GitHub repozitář (zdrojový kód)",
    pl: "Repozytorium GitHub (kod źródłowy)",
    de: "GitHub-Repository (Quellcode)",
    hu: "GitHub tároló (forráskód)",
    sk: "GitHub repozitár (zdrojový kód)",
  },
};

export const mirrorNote = {
  en: "Unofficial mirror",
  cs: "Neoficiální mirror",
  pl: "Nieoficjalne mirror",
  de: "Inoffizieller Mirror",
  hu: "Nem hivatalos mirror",
  sk: "Neoficiálny mirror",
};